from fyers_apiv3 import fyersModel
from django.conf import settings

client_id = settings.FYERS_CONFIG['client_id']
access_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhcGkuZnllcnMuaW4iLCJpYXQiOjE3MzgyNjUzMjgsImV4cCI6MTczODI4MzQ0OCwibmJmIjoxNzM4MjY1MzI4LCJhdWQiOlsieDowIiwieDoxIiwieDoyIiwiZDoxIiwiZDoyIiwieDoxIiwieDowIl0sInN1YiI6ImFjY2Vzc190b2tlbiIsImF0X2hhc2giOiJnQUFBQUFCbm05THdRbWZiVWlMbGFPUnFHV20wUXlyYVhkVjJlQXVIZE9ucnl5ZGxvcWtQODdPLVF5Wm9HbUNReHlSQWFXNms1Q1EzSjJ1Z0pab290T05YTE5KdDAyX1FBR1pWaGV0a2hMb0ZiSkZ1OVFqYk43az0iLCJkaXNwbGF5X25hbWUiOiJBS0lMIFRIQU5HQVZFTCIsIm9tcyI6IksxIiwiaHNtX2tleSI6ImJlY2M0NDU4NmZjN2MyOTFhMWZjYTAwZmVjMjA2YmQ0MjNiOThlZDRiYWY4Mjc3YjZhMWI5Y2U2IiwiaXNEZHBpRW5hYmxlZCI6Ik4iLCJpc010ZkVuYWJsZWQiOiJOIiwiZnlfaWQiOiJZQTI5Mzk2IiwiYXBwVHlwZSI6MTAwLCJwb2FfZmxhZyI6Ik4ifQ.wXVeHxjVSx_6_mhPmw_hgQivtCXolk-7u45uxlXCMjM"

def get_stock_quotes(symbol_quotes):
    fyers = fyersModel.FyersModel(client_id=client_id, token=access_token,is_async=False, log_path="")

    data = {
        "symbols":"NSE:SBIN-EQ,NSE:IDEA-EQ"
    }

    response = fyers.quotes(data=data)
    return response