# Generated by Django 5.1.5 on 2025-07-09 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerPriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltp', models.DecimalField(blank=True, decimal_places=2, help_text='Last Traded Price', max_digits=10, null=True)),
                ('daily_change_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_change_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weekly_change_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weekly_change_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('previous_day_close', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('previous_week_close', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_data', to='dashboard.tickerbase')),
            ],
            options={
                'verbose_name': 'Ticker Price Data',
                'verbose_name_plural': 'Ticker Price Data',
                'db_table': 'dashboard_tickerpricedata',
                'ordering': ['-last_updated'],
            },
        ),
    ]
