# Generated by Django 5.1.5 on 2025-07-04 15:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('xalert', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('strategy_type', models.CharField(choices=[('MA_CROSSOVER', 'Moving Average Crossover'), ('MA_BREAKOUT', 'Moving Average Breakout'), ('MA_SUPPORT', 'Moving Average Support')], max_length=20)),
                ('short_period', models.IntegerField(help_text='Short moving average period')),
                ('long_period', models.IntegerField(help_text='Long moving average period')),
                ('min_volume', models.BigIntegerField(blank=True, help_text='Minimum volume requirement', null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price requirement', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Strategies',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='alerthistory',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='alerthistory',
            name='ticker',
        ),
        migrations.AlterUniqueTogether(
            name='movingaveragesignal',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='movingaveragesignal',
            name='ticker',
        ),
        migrations.CreateModel(
            name='StrategyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_signals', models.IntegerField(default=0)),
                ('buy_signals', models.IntegerField(default=0)),
                ('sell_signals', models.IntegerField(default=0)),
                ('successful_signals', models.IntegerField(default=0)),
                ('success_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='xalert.strategy')),
                ('ticker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.tickerbase')),
            ],
            options={
                'ordering': ['-last_updated'],
                'unique_together': {('strategy', 'ticker', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='StrategySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('BUY', 'Buy Signal'), ('SELL', 'Sell Signal'), ('NEUTRAL', 'Neutral')], max_length=10)),
                ('trigger_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('short_ma_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('long_ma_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('signal_strength', models.DecimalField(blank=True, decimal_places=2, help_text='Signal strength or confidence score', max_digits=5, null=True)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='xalert.strategy')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tickerbase')),
            ],
            options={
                'ordering': ['-triggered_at'],
                'unique_together': {('strategy', 'ticker', 'triggered_at')},
            },
        ),
        migrations.CreateModel(
            name='UserStrategySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('last_alert_sent', models.DateTimeField(blank=True, null=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='xalert.strategy')),
                ('ticker', models.ForeignKey(blank=True, help_text='If specified, only get alerts for this ticker', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.tickerbase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-subscribed_at'],
                'unique_together': {('user', 'strategy', 'ticker')},
            },
        ),
        migrations.CreateModel(
            name='UserAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_alerts', to='xalert.strategysignal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='xalert.userstrategysubscription')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='AlertHistory',
        ),
        migrations.DeleteModel(
            name='MovingAverageSignal',
        ),
    ]
